[project]
name = "a11ytagger"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.6",
    "django-tailwind>=4.2.0",
    "pikepdf>=9.11.0",
    "uvicorn>=0.35.0",
]
